// ── INI parser ────────────────────────────────────────────────────────────────
export function parseIni(text) {
  const result = {}
  let section = '__root__'
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith(';') || line.startsWith('#')) continue
    const sectionMatch = line.match(/^\[(.+)\]$/)
    if (sectionMatch) { section = sectionMatch[1]; result[section] = result[section] || {}; continue }
    const eqIdx = line.indexOf('=')
    if (eqIdx === -1) continue
    const key = line.slice(0, eqIdx).trim()
    const val = line.slice(eqIdx + 1).trim()
    result[section] = result[section] || {}
    result[section][key] = val
  }
  return result
}

// ── server_cfg.ini generator ──────────────────────────────────────────────────
export function generateServerCfg(cfg, adminPassword) {
  const weatherId = {
    'Clear': '3_clear', 'Partly Cloudy': '2_mid_clear', 'Overcast': '1_heavy_clouds',
    'Light Rain': '4_mid_light', 'Heavy Rain': '5_mid_heavy', 'Foggy': '6_early_fog',
  }[cfg.weather] || '3_clear'

  const timeAngles = {
    'Dawn (6:00)': -46, 'Morning (9:00)': -22, 'Midday (12:00)': 0,
    'Afternoon (15:00)': 20, 'Dusk (18:00)': 40, 'Night (21:00)': 62,
  }
  const sunAngle = timeAngles[cfg.time] ?? 0

  const carList = [...new Set(cfg.cars)].join(';')

  const sessions = []
  if (cfg.sessionPractice) sessions.push(`[PRACTICE]\nNAME=Free Practice\nTIME=30\nIS_OPEN=1`)
  if (cfg.sessionQualify)  sessions.push(`[QUALIFY]\nNAME=Qualifying\nTIME=${cfg.qualifyMinutes || 15}\nIS_OPEN=1`)
  if (cfg.sessionRace)     sessions.push(`[RACE]\nNAME=Race\nLAPS=${cfg.raceLength || 20}\nIS_OPEN=0\nJOIN_TYPE=0`)

  const strackerSection = cfg.strackerEnabled
    ? `\n[PLUGIN]\nUDP_PLUGIN_ADDRESS=127.0.0.1:50042\nUDP_PLUGIN_LOCAL_PORT=11000\n`
    : ''

  // Content Manager discovers the wrapper's port by parsing it straight out of
  // the server name shown in the Kunos master server list — no separate lookup
  // step. 'ℹ' (U+2139) is the exact separator character CM's own client and the
  // community server-manager reference implementation both use for this.
  const name = cfg.cmWrapper?.enabled && cfg.cmWrapper?.port
    ? `${cfg.name} ℹ${cfg.cmWrapper.port}`
    : cfg.name

  return `; server_cfg.ini — generated by AC Server Manager / ShinTech
; Server: ${cfg.name}
; Generated: ${new Date().toISOString()}

[SERVER]
NAME=${name}
; PORT= is not a real acServer.exe config key — confirmed by direct testing:
; a real acServer.exe given PORT=9600 logs "Starting TCP listener at port 0"
; (the actual game port was never valid), while UDP_PORT=/TCP_PORT= produces
; the correct "Starting TCP listener at port 9600". This is the real cause
; behind Content Manager's "Failed to ping" error — the game port was never
; actually listening where the server claimed it was.
UDP_PORT=${cfg.port || 9600}
TCP_PORT=${cfg.port || 9600}
HTTP_PORT=${cfg.httpPort || 8081}
; Confirmed against a real acServer.exe: without this key the server runs in
; booking mode (real /INFO reports "pickup":false), which is exactly why
; Content Manager greyed out the join button and said to wait for the next
; booking — new clients aren't allowed to just join, they have to already be
; booked into a slot. With PICKUP_MODE_ENABLED=1, the same /INFO endpoint
; reports "pickup":true and CM lets anyone join immediately, which is the
; normal mode for a friends pickup server (see CLAUDE.md).
PICKUP_MODE_ENABLED=1
MAX_CLIENTS=${cfg.maxClients || 8}
TRACK=${cfg.trackId || 'ks_nordschleife'}
CONFIG_TRACK=${cfg.layoutId || ''}
CARS=${carList}
SUN_ANGLE=${sunAngle}
PASSWORD=${cfg.password || ''}
ADMIN_PASSWORD=${adminPassword || 'admin'}
; This app's servers are for friends over Tailscale/LAN (see CLAUDE.md), never
; the public Kunos server list — nothing generated this key before, which left
; whichever default acServer.exe itself falls back to in charge instead.
REGISTER_TO_LOBBY=0
RACE_OVER_TIME=60
ALLOWED_TYRES_OUT=0
ABS_ALLOWED=${cfg.allowances?.abs ? 1 : 0}
TC_ALLOWED=${cfg.allowances?.tc ? 1 : 0}
STABILITY_ALLOWED=${cfg.allowances?.stability ? 1 : 0}
AUTOCLUTCH_ALLOWED=${cfg.allowances?.autoclutch ? 1 : 0}
TYRE_BLANKETS_ALLOWED=${cfg.allowances?.tyreBlankets ? 1 : 0}
FUEL_RATE=100
DAMAGE_MULTIPLIER=100
TYRE_WEAR_RATE=100
UDP_PLUGIN_LOCAL_PORT=11000
LEGAL_TYRES=
; LOOP_MODE=0 made the server exit the instant its one session rotation
; finished — with zero players connected (the common case right after
; launch) each session completes almost instantly, so the server was
; shutting itself down within milliseconds of starting. 1 loops sessions
; indefinitely, which is what an actually-hostable server needs.
LOOP_MODE=1

; Real acServer.exe (a Go binary) has no flat WEATHER= key under [SERVER] —
; weather is a separate, numbered [WEATHER_N] section. Without at least one,
; acServer.exe's own weather-selection code panics on startup trying to pick
; randomly from an empty list, crashing the server immediately every time.
[WEATHER_0]
GRAPHICS=${weatherId}
BASE_TEMPERATURE_AMBIENT=20
BASE_TEMPERATURE_ROAD=12
VARIATION_AMBIENT=1
VARIATION_ROAD=1
WIND_BASE_SPEED_MIN=0
WIND_BASE_SPEED_MAX=15
WIND_BASE_DIRECTION=0
WIND_VARIATION_DIRECTION=15

${sessions.join('\n\n')}
${strackerSection}`
}

// ── entry_list.ini generator ──────────────────────────────────────────────────
export function generateEntryList(cfg) {
  const slots = []
  const cars = [...new Set(cfg.cars)]
  for (let i = 0; i < cfg.maxClients; i++) {
    const slot = cfg.entrySlots?.[i]
    const car        = slot?.car        || cars[i % cars.length] || ''
    const skin       = slot?.skin       || ''
    const driverName = slot?.driverName || ''
    const guid       = slot?.guid       || ''
    // Confirmed against a real acServer.exe and a real, working preset's own
    // entry_list.ini: section names are [CAR_0], [CAR_1], ... — NOT
    // zero-padded. A zero-padded [CAR_00] isn't recognized as a car slot at
    // all — acServer.exe finds zero cars, logs "Pickup Mode selected and
    // MAX_CLIENTS and entry list size do not match", and silently forces
    // MAX_CLIENTS to 0. That's exactly why Content Manager showed every car
    // as unavailable ("wait for this car / wait for any car") even with
    // nobody connected — the real acServer thought the server had 0 seats.
    // BALLAST=/RESTRICTOR= (not BELLINSTANCED=) are the real, documented
    // keys — matched against the same working reference preset.
    slots.push(`[CAR_${i}]\nMODEL=${car}\nSKIN=${skin}\nSPECTATOR_MODE=0\nDRIVERNAME=${driverName}\nTEAM=\nGUID=${guid}\nBALLAST=0\nRESTRICTOR=0`)
  }
  return `; entry_list.ini — generated by AC Server Manager / ShinTech\n\n` + slots.join('\n\n') + '\n'
}

// ── traffic_config.ini generator ─────────────────────────────────────────────
export function generateTrafficConfigIni(profile, mapName) {
  const { csp, schedule, roster } = profile
  const b = csp.BEHAVIOR, t = csp.TRAFFIC, s = csp.SPAWNING

  const carBlocks = roster
    .filter(c => c.enabled)
    .map((c, i) => `[CAR_${String(i).padStart(2,'0')}]\nMODEL=${c.model}\nSKIN=${c.skin || ''}\nWEIGHT=${c.weight}\nMAX_COUNT=${c.maxCount}`)
    .join('\n\n')

  const scheduleLines = schedule
    .map((v, i) => `DENSITY_HOUR_${String(i).padStart(2,'0')}=${v.toFixed(3)}`)
    .join('\n')

  return `; traffic_config.ini — generated by AC Server Manager / ShinTech
; Map: ${mapName}  Profile: ${profile.name}
; Generated: ${new Date().toISOString()}

[TRAFFIC]
ACTIVE=${t.ACTIVE ? 1 : 0}
MAX_CARS=${t.MAX_CARS}
VARIATION=${t.VARIATION.toFixed(2)}

[BEHAVIOR]
MAX_SPEED_KMH=${b.MAX_SPEED_KMH}
MIN_SPEED_KMH=${b.MIN_SPEED_KMH}
SPEED_LIMIT_MULT=${b.SPEED_LIMIT_MULT.toFixed(2)}
AGGRESSION=${b.AGGRESSION.toFixed(2)}
LANE_DISCIPLINE=${b.LANE_DISCIPLINE.toFixed(2)}
FOLLOWING_GAP=${b.FOLLOWING_GAP.toFixed(1)}
STOPPING_GAP=${b.STOPPING_GAP.toFixed(1)}
BRAKE_DISTANCE_MULT=${b.BRAKE_DISTANCE_MULT.toFixed(2)}
OVERTAKING=${b.OVERTAKING ? 1 : 0}
HORN_ON_OBSTRUCTION=${b.HORN_ON_OBSTRUCTION ? 1 : 0}
LIGHTS_AT_NIGHT=${b.LIGHTS_AT_NIGHT ? 1 : 0}
RANDOM_STOP_CHANCE=${b.RANDOM_STOP_CHANCE.toFixed(3)}

[SPAWNING]
DESPAWN_DISTANCE=${s.DESPAWN_DISTANCE}
SPAWN_DISTANCE_MIN=${s.SPAWN_DISTANCE_MIN}
SPAWN_DISTANCE_MAX=${s.SPAWN_DISTANCE_MAX}
RESPAWN_COOLDOWN=${s.RESPAWN_COOLDOWN.toFixed(1)}
INITIAL_BURST=${s.INITIAL_BURST}

[SCHEDULE]
${scheduleLines}

${carBlocks}
`
}

// ── traffic_config.ini parser (reverse of generateTrafficConfigIni) ──────────
export function parseTrafficIni(iniText) {
  const sections = parseIni(iniText)
  const num  = (v, fallback) => v === undefined ? fallback : Number(v)
  const bool = (v, fallback) => v === undefined ? fallback : (v === '1' || v.toLowerCase() === 'true')

  const t = sections.TRAFFIC  || {}
  const b = sections.BEHAVIOR || {}
  const s = sections.SPAWNING || {}

  const csp = {
    TRAFFIC: {
      ACTIVE:    bool(t.ACTIVE, true),
      MAX_CARS:  num(t.MAX_CARS, 50),
      VARIATION: num(t.VARIATION, 0.3),
    },
    BEHAVIOR: {
      MAX_SPEED_KMH:       num(b.MAX_SPEED_KMH, 80),
      MIN_SPEED_KMH:       num(b.MIN_SPEED_KMH, 30),
      SPEED_LIMIT_MULT:    num(b.SPEED_LIMIT_MULT, 1.0),
      AGGRESSION:          num(b.AGGRESSION, 0.2),
      LANE_DISCIPLINE:     num(b.LANE_DISCIPLINE, 0.85),
      FOLLOWING_GAP:       num(b.FOLLOWING_GAP, 2.5),
      STOPPING_GAP:        num(b.STOPPING_GAP, 4.0),
      BRAKE_DISTANCE_MULT: num(b.BRAKE_DISTANCE_MULT, 1.0),
      OVERTAKING:          bool(b.OVERTAKING, true),
      HORN_ON_OBSTRUCTION: bool(b.HORN_ON_OBSTRUCTION, false),
      LIGHTS_AT_NIGHT:     bool(b.LIGHTS_AT_NIGHT, true),
      RANDOM_STOP_CHANCE:  num(b.RANDOM_STOP_CHANCE, 0),
    },
    SPAWNING: {
      DESPAWN_DISTANCE:   num(s.DESPAWN_DISTANCE, 300),
      SPAWN_DISTANCE_MIN: num(s.SPAWN_DISTANCE_MIN, 150),
      SPAWN_DISTANCE_MAX: num(s.SPAWN_DISTANCE_MAX, 280),
      RESPAWN_COOLDOWN:   num(s.RESPAWN_COOLDOWN, 5.0),
      INITIAL_BURST:      num(s.INITIAL_BURST, 20),
    },
  }

  const scheduleSection = sections.SCHEDULE || {}
  const schedule = Array.from({ length: 24 }, (_, i) => {
    const key = `DENSITY_HOUR_${String(i).padStart(2, '0')}`
    return num(scheduleSection[key], 0.3)
  })

  const carKeys = Object.keys(sections).filter(k => /^CAR_\d+$/.test(k)).sort()
  const roster = carKeys.map((key, i) => {
    const c = sections[key]
    return {
      id: `parsed_${key}_${i}`,
      model: c.MODEL || '',
      skin: c.SKIN || '',
      weight: num(c.WEIGHT, 10),
      maxCount: num(c.MAX_COUNT, 5),
      enabled: true,
    }
  })

  return { csp, schedule, roster }
}

export function generateSettingsJson(profile) {
  const b = profile.csp.BEHAVIOR
  return JSON.stringify({
    version: 2, enabled: true, profile: profile.name,
    maxCars: profile.csp.TRAFFIC.MAX_CARS,
    behavior: {
      aggression: b.AGGRESSION, speedLimitMultiplier: b.SPEED_LIMIT_MULT,
      laneDiscipline: b.LANE_DISCIPLINE, followingGap: b.FOLLOWING_GAP,
      overtaking: b.OVERTAKING, lightsAtNight: b.LIGHTS_AT_NIGHT,
    },
    solIntegration: { enabled: true, useWeatherDensity: true, densitySchedule: profile.schedule },
    cars: profile.roster.filter(c => c.enabled).map(c => ({
      model: c.model, skin: c.skin || null, weight: c.weight, maxCount: c.maxCount,
    })),
  }, null, 2)
}
