// ── INI parser ────────────────────────────────────────────────────────────────
export function parseIni(text) {
  const result = {}
  let section = '__root__'
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim()
    if (!line || line.startsWith(';') || line.startsWith('#')) continue
    const sectionMatch = line.match(/^\[(.+)\]$/)
    if (sectionMatch) { section = sectionMatch[1]; result[section] = result[section] || {}; continue }
    const eqIdx = line.indexOf('=')
    if (eqIdx === -1) continue
    const key = line.slice(0, eqIdx).trim()
    const val = line.slice(eqIdx + 1).trim()
    result[section] = result[section] || {}
    result[section][key] = val
  }
  return result
}

// ── server_cfg.ini generator ──────────────────────────────────────────────────
export function generateServerCfg(cfg, adminPassword) {
  const weatherId = {
    'Clear': '3_clear', 'Partly Cloudy': '2_mid_clear', 'Overcast': '1_heavy_clouds',
    'Light Rain': '4_mid_light', 'Heavy Rain': '5_mid_heavy', 'Foggy': '6_early_fog',
  }[cfg.weather] || '3_clear'

  const timeAngles = {
    'Dawn (6:00)': -46, 'Morning (9:00)': -22, 'Midday (12:00)': 0,
    'Afternoon (15:00)': 20, 'Dusk (18:00)': 40, 'Night (21:00)': 62,
  }
  const sunAngle = timeAngles[cfg.time] ?? 0

  const carList = [...new Set(cfg.cars)].join(';')

  const sessions = []
  if (cfg.sessionPractice) sessions.push(`[PRACTICE]\nNAME=Free Practice\nTIME=30\nIS_OPEN=1`)
  if (cfg.sessionQualify)  sessions.push(`[QUALIFY]\nNAME=Qualifying\nTIME=${cfg.qualifyMinutes || 15}\nIS_OPEN=1`)
  if (cfg.sessionRace)     sessions.push(`[RACE]\nNAME=Race\nLAPS=${cfg.raceLength || 20}\nIS_OPEN=0\nJOIN_TYPE=0`)

  return `; server_cfg.ini — generated by AC Server Manager / ShinTech
; Server: ${cfg.name}
; Generated: ${new Date().toISOString()}

[SERVER]
NAME=${cfg.name}
PORT=${cfg.port || 9600}
HTTP_PORT=${cfg.httpPort || 8081}
MAX_CLIENTS=${cfg.maxClients || 8}
TRACK=${cfg.trackId || 'ks_nordschleife'}
CONFIG_TRACK=${cfg.layoutId || ''}
CARS=${carList}
WEATHER=${weatherId}
SUN_ANGLE=${sunAngle}
PASSWORD=${cfg.password || ''}
ADMIN_PASSWORD=${adminPassword || 'admin'}
RACE_OVER_TIME=60
ALLOWED_TYRES_OUT=0
ABS_ALLOWED=${cfg.allowances?.abs ? 1 : 0}
TC_ALLOWED=${cfg.allowances?.tc ? 1 : 0}
STABILITY_ALLOWED=${cfg.allowances?.stability ? 1 : 0}
AUTOCLUTCH_ALLOWED=${cfg.allowances?.autoclutch ? 1 : 0}
TYRE_BLANKETS_ALLOWED=${cfg.allowances?.tyreBlankets ? 1 : 0}
FUEL_RATE=100
DAMAGE_MULTIPLIER=100
TYRE_WEAR_RATE=100
UDP_PLUGIN_LOCAL_PORT=11000
LEGAL_TYRES=
LOOP_MODE=0

${sessions.join('\n\n')}
`
}

// ── entry_list.ini generator ──────────────────────────────────────────────────
export function generateEntryList(cfg) {
  const slots = []
  const cars = [...new Set(cfg.cars)]
  for (let i = 0; i < cfg.maxClients; i++) {
    const slot = cfg.entrySlots?.[i]
    const car        = slot?.car        || cars[i % cars.length] || ''
    const skin       = slot?.skin       || ''
    const driverName = slot?.driverName || ''
    const guid       = slot?.guid       || ''
    slots.push(`[CAR_${String(i).padStart(2, '0')}]\nMODEL=${car}\nSKIN=${skin}\nSPECTATOR_MODE=0\nDRIVERNAME=${driverName}\nTEAM=\nGUID=${guid}\nBELLINSTANCED=0`)
  }
  return `; entry_list.ini — generated by AC Server Manager / ShinTech\n\n` + slots.join('\n\n') + '\n'
}

// ── traffic_config.ini generator ─────────────────────────────────────────────
export function generateTrafficConfigIni(profile, mapName) {
  const { csp, schedule, roster } = profile
  const b = csp.BEHAVIOR, t = csp.TRAFFIC, s = csp.SPAWNING

  const carBlocks = roster
    .filter(c => c.enabled)
    .map((c, i) => `[CAR_${String(i).padStart(2,'0')}]\nMODEL=${c.model}\nSKIN=${c.skin || ''}\nWEIGHT=${c.weight}\nMAX_COUNT=${c.maxCount}`)
    .join('\n\n')

  const scheduleLines = schedule
    .map((v, i) => `DENSITY_HOUR_${String(i).padStart(2,'0')}=${v.toFixed(3)}`)
    .join('\n')

  return `; traffic_config.ini — generated by AC Server Manager / ShinTech
; Map: ${mapName}  Profile: ${profile.name}
; Generated: ${new Date().toISOString()}

[TRAFFIC]
ACTIVE=${t.ACTIVE ? 1 : 0}
MAX_CARS=${t.MAX_CARS}
VARIATION=${t.VARIATION.toFixed(2)}

[BEHAVIOR]
MAX_SPEED_KMH=${b.MAX_SPEED_KMH}
MIN_SPEED_KMH=${b.MIN_SPEED_KMH}
SPEED_LIMIT_MULT=${b.SPEED_LIMIT_MULT.toFixed(2)}
AGGRESSION=${b.AGGRESSION.toFixed(2)}
LANE_DISCIPLINE=${b.LANE_DISCIPLINE.toFixed(2)}
FOLLOWING_GAP=${b.FOLLOWING_GAP.toFixed(1)}
STOPPING_GAP=${b.STOPPING_GAP.toFixed(1)}
BRAKE_DISTANCE_MULT=${b.BRAKE_DISTANCE_MULT.toFixed(2)}
OVERTAKING=${b.OVERTAKING ? 1 : 0}
HORN_ON_OBSTRUCTION=${b.HORN_ON_OBSTRUCTION ? 1 : 0}
LIGHTS_AT_NIGHT=${b.LIGHTS_AT_NIGHT ? 1 : 0}
RANDOM_STOP_CHANCE=${b.RANDOM_STOP_CHANCE.toFixed(3)}

[SPAWNING]
DESPAWN_DISTANCE=${s.DESPAWN_DISTANCE}
SPAWN_DISTANCE_MIN=${s.SPAWN_DISTANCE_MIN}
SPAWN_DISTANCE_MAX=${s.SPAWN_DISTANCE_MAX}
RESPAWN_COOLDOWN=${s.RESPAWN_COOLDOWN.toFixed(1)}
INITIAL_BURST=${s.INITIAL_BURST}

[SCHEDULE]
${scheduleLines}

${carBlocks}
`
}

// ── traffic_config.ini parser (reverse of generateTrafficConfigIni) ──────────
export function parseTrafficIni(iniText) {
  const sections = parseIni(iniText)
  const num  = (v, fallback) => v === undefined ? fallback : Number(v)
  const bool = (v, fallback) => v === undefined ? fallback : (v === '1' || v.toLowerCase() === 'true')

  const t = sections.TRAFFIC  || {}
  const b = sections.BEHAVIOR || {}
  const s = sections.SPAWNING || {}

  const csp = {
    TRAFFIC: {
      ACTIVE:    bool(t.ACTIVE, true),
      MAX_CARS:  num(t.MAX_CARS, 50),
      VARIATION: num(t.VARIATION, 0.3),
    },
    BEHAVIOR: {
      MAX_SPEED_KMH:       num(b.MAX_SPEED_KMH, 80),
      MIN_SPEED_KMH:       num(b.MIN_SPEED_KMH, 30),
      SPEED_LIMIT_MULT:    num(b.SPEED_LIMIT_MULT, 1.0),
      AGGRESSION:          num(b.AGGRESSION, 0.2),
      LANE_DISCIPLINE:     num(b.LANE_DISCIPLINE, 0.85),
      FOLLOWING_GAP:       num(b.FOLLOWING_GAP, 2.5),
      STOPPING_GAP:        num(b.STOPPING_GAP, 4.0),
      BRAKE_DISTANCE_MULT: num(b.BRAKE_DISTANCE_MULT, 1.0),
      OVERTAKING:          bool(b.OVERTAKING, true),
      HORN_ON_OBSTRUCTION: bool(b.HORN_ON_OBSTRUCTION, false),
      LIGHTS_AT_NIGHT:     bool(b.LIGHTS_AT_NIGHT, true),
      RANDOM_STOP_CHANCE:  num(b.RANDOM_STOP_CHANCE, 0),
    },
    SPAWNING: {
      DESPAWN_DISTANCE:   num(s.DESPAWN_DISTANCE, 300),
      SPAWN_DISTANCE_MIN: num(s.SPAWN_DISTANCE_MIN, 150),
      SPAWN_DISTANCE_MAX: num(s.SPAWN_DISTANCE_MAX, 280),
      RESPAWN_COOLDOWN:   num(s.RESPAWN_COOLDOWN, 5.0),
      INITIAL_BURST:      num(s.INITIAL_BURST, 20),
    },
  }

  const scheduleSection = sections.SCHEDULE || {}
  const schedule = Array.from({ length: 24 }, (_, i) => {
    const key = `DENSITY_HOUR_${String(i).padStart(2, '0')}`
    return num(scheduleSection[key], 0.3)
  })

  const carKeys = Object.keys(sections).filter(k => /^CAR_\d+$/.test(k)).sort()
  const roster = carKeys.map((key, i) => {
    const c = sections[key]
    return {
      id: `parsed_${key}_${i}`,
      model: c.MODEL || '',
      skin: c.SKIN || '',
      weight: num(c.WEIGHT, 10),
      maxCount: num(c.MAX_COUNT, 5),
      enabled: true,
    }
  })

  return { csp, schedule, roster }
}

export function generateSettingsJson(profile) {
  const b = profile.csp.BEHAVIOR
  return JSON.stringify({
    version: 2, enabled: true, profile: profile.name,
    maxCars: profile.csp.TRAFFIC.MAX_CARS,
    behavior: {
      aggression: b.AGGRESSION, speedLimitMultiplier: b.SPEED_LIMIT_MULT,
      laneDiscipline: b.LANE_DISCIPLINE, followingGap: b.FOLLOWING_GAP,
      overtaking: b.OVERTAKING, lightsAtNight: b.LIGHTS_AT_NIGHT,
    },
    solIntegration: { enabled: true, useWeatherDensity: true, densitySchedule: profile.schedule },
    cars: profile.roster.filter(c => c.enabled).map(c => ({
      model: c.model, skin: c.skin || null, weight: c.weight, maxCount: c.maxCount,
    })),
  }, null, 2)
}
