// Same preset links as the Electron app's src/renderer/views/LinksView.jsx —
// duplicated as a literal copy rather than imported across the pwa/ ↔ src/
// build boundary (see colors.js for why). Update both if the list changes.
export const CATEGORIES = [
  { id: 'tracks_cars',  label: 'Tracks & Cars',  emoji: '🏎️' },
  { id: 'tools_apps',   label: 'Tools & Apps',   emoji: '🛠️' },
  { id: 'communities',  label: 'Communities',    emoji: '💬' },
  { id: 'youtube',      label: 'YouTube',        emoji: '▶️' },
  { id: 'setup_guides', label: 'Setup & Guides', emoji: '📖' },
  { id: 'other',        label: 'Other',          emoji: '🔗' },
]

export const PRESET_LINKS = [
  { id: 'p_rd_tracks', category: 'tracks_cars', name: 'RaceDepartment — Tracks', url: 'https://www.racedepartment.com/downloads/categories/tracks.4/',
    description: 'The biggest community mod archive for AC. Start here.' },
  { id: 'p_overtake', category: 'tracks_cars', name: 'Overtake.gg', url: 'https://www.overtake.gg/downloads/categories/assetto-corsa.9/',
    description: 'Modern RD successor. Clean UI, active uploads.' },
  { id: 'p_ac_content', category: 'tracks_cars', name: 'AC Content (Google Drive collections)', url: 'https://acstuff.ru/app/',
    description: "Content Manager's built-in mod browser." },
  { id: 'p_rd_cars', category: 'tracks_cars', name: 'RD — Cars', url: 'https://www.racedepartment.com/downloads/categories/cars.5/',
    description: 'Community car mods, everything from road cars to race prototypes.' },
  { id: 'p_cm', category: 'tools_apps', name: 'Content Manager', url: 'https://acstuff.ru/app/',
    description: "The essential AC launcher. If you don't have this, get it now." },
  { id: 'p_csp', category: 'tools_apps', name: 'Custom Shaders Patch (CSP)', url: 'https://acstuff.ru/patch/',
    description: 'Unlocks advanced graphics, AI traffic, and hundreds of fixes.' },
  { id: 'p_sol', category: 'tools_apps', name: 'sol (WeatherFX)', url: 'https://www.racedepartment.com/downloads/sol.24914/',
    description: 'The gold standard weather mod for AC.' },
  { id: 'p_crewchief', category: 'tools_apps', name: 'CrewChief', url: 'https://thecrewchief.org/',
    description: 'Voice-activated spotter and race engineer. Works with AC.' },
  { id: 'p_helicorsa', category: 'tools_apps', name: 'Helicorsa', url: 'https://www.racedepartment.com/downloads/helicorsa.10296/',
    description: 'Proximity radar overlay. Essential for wheel-to-wheel racing.' },
  { id: 'p_stracker', category: 'tools_apps', name: 'stracker', url: 'https://strikerarena.com/stracker',
    description: 'Lap time tracking and server statistics.' },
  { id: 'p_asm', category: 'tools_apps', name: 'AC Server Manager (original)', url: 'https://github.com/JustaPenguin/assetto-server-manager',
    description: 'The open source server manager that inspired parts of ShinRacer.' },
  { id: 'p_reddit', category: 'communities', name: 'Assetto Corsa subreddit', url: 'https://www.reddit.com/r/assettocorsa/',
    description: 'General AC community. Good for mod discovery and setup help.' },
  { id: 'p_rd_forums', category: 'communities', name: 'RaceDepartment Forums', url: 'https://www.racedepartment.com/forums/assetto-corsa.165/',
    description: 'Deep technical discussions, mod releases, setup sharing.' },
  { id: 'p_csp_discord', category: 'communities', name: 'CSP Discord', url: 'https://discord.gg/assetto-corsa',
    description: 'Official-ish AC community Discord. CSP devs sometimes appear.' },
  { id: 'p_srp', category: 'communities', name: 'Shutoko Revival Project', url: 'https://www.shutoko.eu/',
    description: 'Home of SRP. Check here for updates and traffic configs.' },
  { id: 'p_jimmy', category: 'youtube', name: 'Jimmy Broadbent', url: 'https://www.youtube.com/@JimmyBroadbent',
    description: 'The gateway drug. High quality AC content and reviews.' },
  { id: 'p_jardier', category: 'youtube', name: 'Jardier', url: 'https://www.youtube.com/@Jardier',
    description: 'Drift-focused. Great for technique and car setup inspiration.' },
  { id: 'p_aris', category: 'youtube', name: 'Aris Drives', url: 'https://www.youtube.com/@ArisDrives',
    description: 'Kunos physics lead. Deep dives into car setup and AC mechanics.' },
  { id: 'p_morad', category: 'youtube', name: 'Daniel Morad', url: 'https://www.youtube.com/@DanielMorad',
    description: 'Real racing driver doing sim content. Surprisingly useful setups.' },
  { id: 'p_lut', category: 'setup_guides', name: 'LUT Generator (FFB)', url: 'https://www.racedepartment.com/downloads/lut-generator-for-ac.9740/',
    description: 'Generate a custom force feedback lookup table for your wheel.' },
  { id: 'p_setup_guide', category: 'setup_guides', name: 'AC Setup Guide (RD)', url: 'https://www.racedepartment.com/threads/beginners-guide-to-car-setup.133264/',
    description: 'Beginner-friendly car setup fundamentals.' },
  { id: 'p_csp_wiki', category: 'setup_guides', name: 'CSP Wiki', url: 'https://github.com/ac-custom-shaders-patch/acc-lua-documentation',
    description: 'Technical CSP documentation. For the adventurous.' },
]
